package net.fawnoculus.ntm.datagen.tags;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.fawnoculus.ntm.blocks.ModBlocks;
import net.fawnoculus.ntm.NTM;
import net.fawnoculus.ntm.misc.tags.ModBlockTags;
import net.minecraft.block.Block;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class BlockTagProvider extends FabricTagProvider<Block> {
  public BlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
    super(output, RegistryKeys.BLOCK, registriesFuture);
  }
  
  
  @Override
  protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
    getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)
        .add(ModBlocks.URANIUM_ORE)
        .add(ModBlocks.SCORCHED_URANIUM_ORE)
        .add(ModBlocks.TITANIUM_ORE)
        .add(ModBlocks.SULFUR_ORE)
        .add(ModBlocks.THORIUM_ORE)
        .add(ModBlocks.NITER_ORE)
        .add(ModBlocks.TUNGSTEN_ORE)
        .add(ModBlocks.ALUMINIUM_BEARING_ORE)
        .add(ModBlocks.FLUORITE_ORE)
        .add(ModBlocks.LEAD_ORE)
        .add(ModBlocks.SCHRABIDIUM_ORE)
        .add(ModBlocks.BERYLLIUM_ORE)
        .add(ModBlocks.AUSTRALIUM_ORE)
        .add(ModBlocks.RARE_EARTH_ORE)
        .add(ModBlocks.COBALT_ORE)
        .add(ModBlocks.CINNEBAR_ORE)
        .add(ModBlocks.COLTAN_ORE)
        .add(ModBlocks.LIGNITE_ORE)
        .add(ModBlocks.ASBESTOS_ORE)
        .add(ModBlocks.OIL_DEPOSIT)
        .add(ModBlocks.EMPTY_OIL_DEPOSIT)
        .add(ModBlocks.ALUMINIUM_ORE_CLUSTER)
        .add(ModBlocks.COPPER_ORE_CLUSTER)
        .add(ModBlocks.IRON_ORE_CLUSTER)
        .add(ModBlocks.TITANIUM_ORE_CLUSTER)
        .add(ModBlocks.ALEXANDRITE_ORE)
        .add(ModBlocks.VOLCANIC_BASALT)
        .add(ModBlocks.SULFUR_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.FLUORITE_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.ASBESTOS_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.GEM_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.MOLYSITE_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.SMOLDERING_NETHERRACK)
        .add(ModBlocks.NETHER_COAL_ORE)
        .add(ModBlocks.NETHER_URANIUM_ORE)
        .add(ModBlocks.SCORCHED_NETHER_URANIUM_ORE)
        .add(ModBlocks.NETHER_PLUTONIUM_ORE)
        .add(ModBlocks.NETHER_TUNGSTEN_ORE)
        .add(ModBlocks.NETHER_SULFUR_ORE)
        .add(ModBlocks.NETHER_PHOSPHORUS_ORE)
        .add(ModBlocks.NETHER_COBALT_ORE)
        .add(ModBlocks.NETHER_SCHRABIDIUM_ORE)
        .add(ModBlocks.SCHIST_IRON_ORE)
        .add(ModBlocks.SCHIST_GOLD_ORE)
        .add(ModBlocks.SCHIST_URANIUM_ORE)
        .add(ModBlocks.SCORCHED_SCHIST_URANIUM_ORE)
        .add(ModBlocks.SCHIST_COPPER_ORE)
        .add(ModBlocks.SCHIST_ASBESTOS_ORE)
        .add(ModBlocks.SCHIST_LITHIUM_ORE)
        .add(ModBlocks.SCHIST_SCHRABIDIUM_ORE)
        .add(ModBlocks.SCHIST_RARE_EARTH_ORE)
        .add(ModBlocks.GAS_SHALE)
        .add(ModBlocks.OSMIRIDIUM_INFUSED_TEKTITE)
        .add(ModBlocks.TRIXITE_ORE)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.NEEDS_DIAMOND_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_WOODEN_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_WOODEN_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_STONE_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_IRON_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_DIAMOND_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_STEEL_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_TITANIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_ADVANCED_ALLOY_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_CMB_STEEL_TOOL)
        .addTag(ModBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_DESH_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_COBALT_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_DECORATED_COBALT_TOOL)
        .addTag(ModBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_STARMETAL_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_SCHRABIDIUM_TOOL)
        .addTag(ModBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_BISMUTH_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_MOLTEN_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_CHLOROPHYTE_TOOL)
        .addTag(ModBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(ModBlockTags.INCORRECT_FOR_MESE_TOOL)
        .setReplace(false);
    
    getOrCreateTagBuilder(ModBlockTags.DEPTH_ROCK)
        .add(ModBlocks.DEPTH_ROCK)
        .add(ModBlocks.DEPTH_CINNABAR_ORE)
        .add(ModBlocks.DEPTH_ZIRCONIUM_ORE)
        .add(ModBlocks.DEPTH_BORAX_ORE)
        .add(ModBlocks.DEPTH_IRON_ORE_CLUSTER)
        .add(ModBlocks.DEPTH_TITANIUM_ORE_CLUSTER)
        .add(ModBlocks.DEPTH_TUNGSTEN_ORE_CLUSTER)
        .add(ModBlocks.NETHER_DEPTH_ROCK)
        .add(ModBlocks.NETHER_DEPTH_NEODYMIUM_ORE)
        .setReplace(false);
    
    getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
        .add(ModBlocks.URANIUM_ORE)
        .add(ModBlocks.SCORCHED_URANIUM_ORE)
        .add(ModBlocks.TITANIUM_ORE)
        .add(ModBlocks.SULFUR_ORE)
        .add(ModBlocks.THORIUM_ORE)
        .add(ModBlocks.NITER_ORE)
        .add(ModBlocks.TUNGSTEN_ORE)
        .add(ModBlocks.ALUMINIUM_BEARING_ORE)
        .add(ModBlocks.FLUORITE_ORE)
        .add(ModBlocks.LEAD_ORE)
        .add(ModBlocks.SCHRABIDIUM_ORE)
        .add(ModBlocks.BERYLLIUM_ORE)
        .add(ModBlocks.AUSTRALIUM_ORE)
        .add(ModBlocks.RARE_EARTH_ORE)
        .add(ModBlocks.COBALT_ORE)
        .add(ModBlocks.CINNEBAR_ORE)
        .add(ModBlocks.COLTAN_ORE)
        .add(ModBlocks.LIGNITE_ORE)
        .add(ModBlocks.ASBESTOS_ORE)
        .add(ModBlocks.OIL_DEPOSIT)
        .add(ModBlocks.EMPTY_OIL_DEPOSIT)
        .add(ModBlocks.ALUMINIUM_ORE_CLUSTER)
        .add(ModBlocks.COPPER_ORE_CLUSTER)
        .add(ModBlocks.IRON_ORE_CLUSTER)
        .add(ModBlocks.TITANIUM_ORE_CLUSTER)
        .add(ModBlocks.DEPTH_ROCK)
        .add(ModBlocks.DEPTH_CINNABAR_ORE)
        .add(ModBlocks.DEPTH_ZIRCONIUM_ORE)
        .add(ModBlocks.DEPTH_BORAX_ORE)
        .add(ModBlocks.DEPTH_IRON_ORE_CLUSTER)
        .add(ModBlocks.DEPTH_TITANIUM_ORE_CLUSTER)
        .add(ModBlocks.DEPTH_TUNGSTEN_ORE_CLUSTER)
        .add(ModBlocks.ALEXANDRITE_ORE)
        .add(ModBlocks.VOLCANIC_BASALT)
        .add(ModBlocks.SULFUR_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.FLUORITE_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.ASBESTOS_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.GEM_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.MOLYSITE_RICH_VOLCANIC_BASALT)
        .add(ModBlocks.SMOLDERING_NETHERRACK)
        .add(ModBlocks.NETHER_COAL_ORE)
        .add(ModBlocks.NETHER_URANIUM_ORE)
        .add(ModBlocks.SCORCHED_NETHER_URANIUM_ORE)
        .add(ModBlocks.NETHER_PLUTONIUM_ORE)
        .add(ModBlocks.NETHER_TUNGSTEN_ORE)
        .add(ModBlocks.NETHER_SULFUR_ORE)
        .add(ModBlocks.NETHER_PHOSPHORUS_ORE)
        .add(ModBlocks.NETHER_COBALT_ORE)
        .add(ModBlocks.NETHER_SCHRABIDIUM_ORE)
        .add(ModBlocks.NETHER_DEPTH_ROCK)
        .add(ModBlocks.NETHER_DEPTH_NEODYMIUM_ORE)
        .add(ModBlocks.METEORITE_BLOCK)
        .add(ModBlocks.BROKEN_METEORITE_BLOCK)
        .add(ModBlocks.METEORITE_COBBLESTONE)
        .add(ModBlocks.HOT_METEORITE_COBBLESTONE)
        .add(ModBlocks.METEORITE_TREASURE_BLOCK)
        .add(ModBlocks.METEOR_IRON_ORE)
        .add(ModBlocks.METEOR_COPPER_ORE)
        .add(ModBlocks.METEOR_ALUMINIUM_ORE)
        .add(ModBlocks.METEOR_RARE_EARTH_ORE)
        .add(ModBlocks.METEOR_COBALT_ORE)
        .add(ModBlocks.GRAPHITIC_SCHIST)
        .add(ModBlocks.SCHIST_IRON_ORE)
        .add(ModBlocks.SCHIST_GOLD_ORE)
        .add(ModBlocks.SCHIST_URANIUM_ORE)
        .add(ModBlocks.SCORCHED_SCHIST_URANIUM_ORE)
        .add(ModBlocks.SCHIST_COPPER_ORE)
        .add(ModBlocks.SCHIST_ASBESTOS_ORE)
        .add(ModBlocks.SCHIST_LITHIUM_ORE)
        .add(ModBlocks.SCHIST_SCHRABIDIUM_ORE)
        .add(ModBlocks.SCHIST_RARE_EARTH_ORE)
        .add(ModBlocks.GAS_SHALE)
        .add(ModBlocks.BAUXITE)
        .add(ModBlocks.CHRYSOTILE)
        .add(ModBlocks.HEMATITE)
        .add(ModBlocks.LIMESTONE)
        .add(ModBlocks.MALACHITE)
        .add(ModBlocks.SULFUROUS_STONE)
        .add(ModBlocks.TEKTITE)
        .add(ModBlocks.OSMIRIDIUM_INFUSED_TEKTITE)
        .add(ModBlocks.TRIXITE_ORE)
        .setReplace(false);
  }
  
  @Override
  public String getName() {
    return NTM.MOD_NAME + " Block-Tag Provider";
  }
}
