package net.fawnoculus.ntm.datagen.tags;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.fawnoculus.ntm.blocks.NTMBlocks;
import net.fawnoculus.ntm.NTM;
import net.fawnoculus.ntm.misc.tags.NTMBlockTags;
import net.minecraft.block.Block;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;

import java.util.concurrent.CompletableFuture;

public class NTMBlockTagProvider extends FabricTagProvider<Block> {
  public NTMBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
    super(output, RegistryKeys.BLOCK, registriesFuture);
  }
  
  
  @Override
  protected void configure(RegistryWrapper.WrapperLookup wrapperLookup) {
    getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)
        .add(NTMBlocks.URANIUM_ORE)
        .add(NTMBlocks.SCORCHED_URANIUM_ORE)
        .add(NTMBlocks.TITANIUM_ORE)
        .add(NTMBlocks.SULFUR_ORE)
        .add(NTMBlocks.THORIUM_ORE)
        .add(NTMBlocks.NITER_ORE)
        .add(NTMBlocks.TUNGSTEN_ORE)
        .add(NTMBlocks.ALUMINIUM_BEARING_ORE)
        .add(NTMBlocks.FLUORITE_ORE)
        .add(NTMBlocks.LEAD_ORE)
        .add(NTMBlocks.SCHRABIDIUM_ORE)
        .add(NTMBlocks.BERYLLIUM_ORE)
        .add(NTMBlocks.AUSTRALIUM_ORE)
        .add(NTMBlocks.RARE_EARTH_ORE)
        .add(NTMBlocks.COBALT_ORE)
        .add(NTMBlocks.CINNEBAR_ORE)
        .add(NTMBlocks.COLTAN_ORE)
        .add(NTMBlocks.LIGNITE_ORE)
        .add(NTMBlocks.ASBESTOS_ORE)
        .add(NTMBlocks.OIL_DEPOSIT)
        .add(NTMBlocks.EMPTY_OIL_DEPOSIT)
        .add(NTMBlocks.ALUMINIUM_ORE_CLUSTER)
        .add(NTMBlocks.COPPER_ORE_CLUSTER)
        .add(NTMBlocks.IRON_ORE_CLUSTER)
        .add(NTMBlocks.TITANIUM_ORE_CLUSTER)
        .add(NTMBlocks.ALEXANDRITE_ORE)
        .add(NTMBlocks.VOLCANIC_BASALT)
        .add(NTMBlocks.SULFUR_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.FLUORITE_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.ASBESTOS_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.GEM_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.MOLYSITE_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.SMOLDERING_NETHERRACK)
        .add(NTMBlocks.NETHER_COAL_ORE)
        .add(NTMBlocks.NETHER_URANIUM_ORE)
        .add(NTMBlocks.SCORCHED_NETHER_URANIUM_ORE)
        .add(NTMBlocks.NETHER_PLUTONIUM_ORE)
        .add(NTMBlocks.NETHER_TUNGSTEN_ORE)
        .add(NTMBlocks.NETHER_SULFUR_ORE)
        .add(NTMBlocks.NETHER_PHOSPHORUS_ORE)
        .add(NTMBlocks.NETHER_COBALT_ORE)
        .add(NTMBlocks.NETHER_SCHRABIDIUM_ORE)
        .add(NTMBlocks.SCHIST_IRON_ORE)
        .add(NTMBlocks.SCHIST_GOLD_ORE)
        .add(NTMBlocks.SCHIST_URANIUM_ORE)
        .add(NTMBlocks.SCORCHED_SCHIST_URANIUM_ORE)
        .add(NTMBlocks.SCHIST_COPPER_ORE)
        .add(NTMBlocks.SCHIST_ASBESTOS_ORE)
        .add(NTMBlocks.SCHIST_LITHIUM_ORE)
        .add(NTMBlocks.SCHIST_SCHRABIDIUM_ORE)
        .add(NTMBlocks.SCHIST_RARE_EARTH_ORE)
        .add(NTMBlocks.GAS_SHALE)
        .add(NTMBlocks.OSMIRIDIUM_INFUSED_TEKTITE)
        .add(NTMBlocks.TRIXITE_ORE)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.NEEDS_DIAMOND_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_WOODEN_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_WOODEN_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_STONE_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_IRON_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(BlockTags.INCORRECT_FOR_DIAMOND_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_STEEL_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_TITANIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(BlockTags.NEEDS_DIAMOND_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_ADVANCED_ALLOY_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_CMB_STEEL_TOOL)
        .addTag(NTMBlockTags.NEEDS_NETHERRITE_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_DESH_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_COBALT_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_DECORATED_COBALT_TOOL)
        .addTag(NTMBlockTags.NEEDS_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_STARMETAL_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_SCHRABIDIUM_TOOL)
        .addTag(NTMBlockTags.NEEDS_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_BISMUTH_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_MOLTEN_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_CHLOROPHYTE_TOOL)
        .addTag(NTMBlockTags.NEEDS_MESE_TOOL)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.INCORRECT_FOR_MESE_TOOL)
        .setReplace(false);
    
    getOrCreateTagBuilder(NTMBlockTags.DEPTH_ROCK)
        .add(NTMBlocks.DEPTH_ROCK)
        .add(NTMBlocks.DEPTH_CINNABAR_ORE)
        .add(NTMBlocks.DEPTH_ZIRCONIUM_ORE)
        .add(NTMBlocks.DEPTH_BORAX_ORE)
        .add(NTMBlocks.DEPTH_IRON_ORE_CLUSTER)
        .add(NTMBlocks.DEPTH_TITANIUM_ORE_CLUSTER)
        .add(NTMBlocks.DEPTH_TUNGSTEN_ORE_CLUSTER)
        .add(NTMBlocks.NETHER_DEPTH_ROCK)
        .add(NTMBlocks.NETHER_DEPTH_NEODYMIUM_ORE)
        .setReplace(false);
    
    getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
        .add(NTMBlocks.URANIUM_ORE)
        .add(NTMBlocks.SCORCHED_URANIUM_ORE)
        .add(NTMBlocks.TITANIUM_ORE)
        .add(NTMBlocks.SULFUR_ORE)
        .add(NTMBlocks.THORIUM_ORE)
        .add(NTMBlocks.NITER_ORE)
        .add(NTMBlocks.TUNGSTEN_ORE)
        .add(NTMBlocks.ALUMINIUM_BEARING_ORE)
        .add(NTMBlocks.FLUORITE_ORE)
        .add(NTMBlocks.LEAD_ORE)
        .add(NTMBlocks.SCHRABIDIUM_ORE)
        .add(NTMBlocks.BERYLLIUM_ORE)
        .add(NTMBlocks.AUSTRALIUM_ORE)
        .add(NTMBlocks.RARE_EARTH_ORE)
        .add(NTMBlocks.COBALT_ORE)
        .add(NTMBlocks.CINNEBAR_ORE)
        .add(NTMBlocks.COLTAN_ORE)
        .add(NTMBlocks.LIGNITE_ORE)
        .add(NTMBlocks.ASBESTOS_ORE)
        .add(NTMBlocks.OIL_DEPOSIT)
        .add(NTMBlocks.EMPTY_OIL_DEPOSIT)
        .add(NTMBlocks.ALUMINIUM_ORE_CLUSTER)
        .add(NTMBlocks.COPPER_ORE_CLUSTER)
        .add(NTMBlocks.IRON_ORE_CLUSTER)
        .add(NTMBlocks.TITANIUM_ORE_CLUSTER)
        .add(NTMBlocks.DEPTH_ROCK)
        .add(NTMBlocks.DEPTH_CINNABAR_ORE)
        .add(NTMBlocks.DEPTH_ZIRCONIUM_ORE)
        .add(NTMBlocks.DEPTH_BORAX_ORE)
        .add(NTMBlocks.DEPTH_IRON_ORE_CLUSTER)
        .add(NTMBlocks.DEPTH_TITANIUM_ORE_CLUSTER)
        .add(NTMBlocks.DEPTH_TUNGSTEN_ORE_CLUSTER)
        .add(NTMBlocks.ALEXANDRITE_ORE)
        .add(NTMBlocks.VOLCANIC_BASALT)
        .add(NTMBlocks.SULFUR_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.FLUORITE_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.ASBESTOS_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.GEM_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.MOLYSITE_RICH_VOLCANIC_BASALT)
        .add(NTMBlocks.SMOLDERING_NETHERRACK)
        .add(NTMBlocks.NETHER_COAL_ORE)
        .add(NTMBlocks.NETHER_URANIUM_ORE)
        .add(NTMBlocks.SCORCHED_NETHER_URANIUM_ORE)
        .add(NTMBlocks.NETHER_PLUTONIUM_ORE)
        .add(NTMBlocks.NETHER_TUNGSTEN_ORE)
        .add(NTMBlocks.NETHER_SULFUR_ORE)
        .add(NTMBlocks.NETHER_PHOSPHORUS_ORE)
        .add(NTMBlocks.NETHER_COBALT_ORE)
        .add(NTMBlocks.NETHER_SCHRABIDIUM_ORE)
        .add(NTMBlocks.NETHER_DEPTH_ROCK)
        .add(NTMBlocks.NETHER_DEPTH_NEODYMIUM_ORE)
        .add(NTMBlocks.METEORITE_BLOCK)
        .add(NTMBlocks.BROKEN_METEORITE_BLOCK)
        .add(NTMBlocks.METEORITE_COBBLESTONE)
        .add(NTMBlocks.HOT_METEORITE_COBBLESTONE)
        .add(NTMBlocks.METEORITE_TREASURE_BLOCK)
        .add(NTMBlocks.METEOR_IRON_ORE)
        .add(NTMBlocks.METEOR_COPPER_ORE)
        .add(NTMBlocks.METEOR_ALUMINIUM_ORE)
        .add(NTMBlocks.METEOR_RARE_EARTH_ORE)
        .add(NTMBlocks.METEOR_COBALT_ORE)
        .add(NTMBlocks.GRAPHITIC_SCHIST)
        .add(NTMBlocks.SCHIST_IRON_ORE)
        .add(NTMBlocks.SCHIST_GOLD_ORE)
        .add(NTMBlocks.SCHIST_URANIUM_ORE)
        .add(NTMBlocks.SCORCHED_SCHIST_URANIUM_ORE)
        .add(NTMBlocks.SCHIST_COPPER_ORE)
        .add(NTMBlocks.SCHIST_ASBESTOS_ORE)
        .add(NTMBlocks.SCHIST_LITHIUM_ORE)
        .add(NTMBlocks.SCHIST_SCHRABIDIUM_ORE)
        .add(NTMBlocks.SCHIST_RARE_EARTH_ORE)
        .add(NTMBlocks.GAS_SHALE)
        .add(NTMBlocks.BAUXITE)
        .add(NTMBlocks.CHRYSOTILE)
        .add(NTMBlocks.HEMATITE)
        .add(NTMBlocks.LIMESTONE)
        .add(NTMBlocks.MALACHITE)
        .add(NTMBlocks.SULFUROUS_STONE)
        .add(NTMBlocks.TEKTITE)
        .add(NTMBlocks.OSMIRIDIUM_INFUSED_TEKTITE)
        .add(NTMBlocks.TRIXITE_ORE)
        .setReplace(false);
    
    getOrCreateTagBuilder(NTMBlockTags.BIG_AXE_MINEABLE)
        .addOptionalTag(BlockTags.AXE_MINEABLE)
        .addOptionalTag(BlockTags.HOE_MINEABLE)
        .setReplace(false);
    getOrCreateTagBuilder(NTMBlockTags.BIG_PICKAXE_MINEABLE)
        .addOptionalTag(BlockTags.PICKAXE_MINEABLE)
        .addOptionalTag(BlockTags.SHOVEL_MINEABLE)
        .setReplace(false);
  }
  
  @Override
  public String getName() {
    return NTM.MOD_NAME + " Block-Tag Provider";
  }
}
